---
- name: Ensure the BIOS configuration script is present
  copy:
    src: set_smc_boot_order.sh
    dest: /home/sysadmin/set_smc_boot_order.sh
    mode: '0755'

- name: Apply BIOS boot order and reboot the server
  command: "/home/sysadmin/set_smc_boot_order.sh {{ ipmi_address }} {{ ipmi_user }} '{{ ipmi_pass }}' {{ bios_boot_order | join(' ') }}"
  register: bios_script_result
  changed_when: "'BIOS configuration applied successfully' in bios_script_result.stdout"
