---
- hosts: console_nodes
  gather_facts: no
  become: yes
  tasks:
    - name: Check if SUM is installed
      stat:
        path: /home/sysadmin/sum_2.14.0_Linux_x86_64/sum
      register: sum_check
      delegate_to: localhost

    - name: Download and extract SUM
      unarchive:
        src: https://www.supermicro.com/Bios/sw_download/698/sum_2.14.0_Linux_x86_64_20240215.tar.gz
        dest: /home/sysadmin/
        remote_src: yes
      when: not sum_check.stat.exists
      delegate_to: localhost

    - name: Create redfish credentials file for root
      template:
        src: redfish_credentials.j2
        dest: /root/.redfish_credentials
        owner: root
        group: root
        mode: '0600'
      vars:
        username: "{{ ipmi_user }}"
        password: "{{ ipmi_pass }}"
      delegate_to: localhost

    - name: Set boot order
      ansible.builtin.command: /home/sysadmin/ansible-provisioning-server/set_boot_order.py {{ inventory_hostname }} pxe hdd
      environment:
        IPMI_USER: "{{ ipmi_user }}"
        IPMI_PASS: "{{ ipmi_pass }}"
      delegate_to: localhost
