---
- hosts: console_nodes
  gather_facts: no
  become: yes
  tasks:
    - name: Check if SUM is installed
      stat:
        path: /home/sysadmin/sum_2.14.0_Linux_x86_64/sum
      register: sum_check
      delegate_to: localhost

    - name: Download and extract SUM
      unarchive:
        src: https://www.supermicro.com/Bios/sw_download/698/sum_2.14.0_Linux_x86_64_20240215.tar.gz
        dest: /home/sysadmin/
        remote_src: yes
      when: not sum_check.stat.exists
      delegate_to: localhost

    - name: Verify redfish credentials file exists
      stat:
        path: /home/sysadmin/.redfish_credentials
      register: redfish_creds_check
      delegate_to: localhost
      
    - name: Fail if redfish credentials not configured
      fail:
        msg: |
          Redfish credentials file not found. Please configure:
          1. cp .redfish_credentials.example .redfish_credentials
          2. Edit .redfish_credentials with your BMC credentials
          3. chmod 600 .redfish_credentials
      when: not redfish_creds_check.stat.exists
      delegate_to: localhost

    - name: Copy redfish credentials to root home directory
      copy:
        src: /home/sysadmin/.redfish_credentials
        dest: /root/.redfish_credentials
        owner: root
        group: root
        mode: '0600'
        remote_src: yes
      delegate_to: localhost

    - name: Set boot order using redfish.py
      ansible.builtin.command: /home/sysadmin/ansible-provisioning-server/redfish.py {{ inventory_hostname }} set-boot-to-bios
      delegate_to: localhost
