---
- name: Optimized Provisioning Server Setup
  hosts: localhost
  connection: local
  become: yes
  
  pre_tasks:
    - name: Verify redfish credentials file exists
      stat:
        path: /home/sysadmin/.redfish_credentials
      register: redfish_creds_check
      failed_when: not redfish_creds_check.stat.exists
      tags:
        - validation
        - always
      
    - name: Consolidated package installation
      block:
        - name: Update apt cache once
          apt:
            update_cache: yes
            cache_valid_time: 3600
          tags:
            - packages
            - foundation
            
        - name: Install all required packages in single operation
          apt:
            name:
              # Common packages
              - vim
              - git
              - curl
              - wget
              - unzip
              - zstd
              - cpio
              - file
              # Network packages
              - bridge-utils
              - ethtool
              - iptables
              - iptables-persistent
              # Service packages
              - dnsmasq
              - tftp-hpa
              - nginx
              - php8.3-fpm
              - php8.3-zip
              - php8.3-mbstring
              - php8.3-xml
              - python3
              - python3-pip
              - python3-requests
              - python3-urllib3
              # Docker prerequisites
              - ca-certificates
              - gnupg
            state: present
          register: package_install
          tags:
            - packages
            - foundation
            
        - name: Set package installation fact
          set_fact:
            packages_changed: "{{ package_install.changed }}"
          tags:
            - packages
      tags:
        - always

  roles:
    - role: common
      tags: 
        - foundation
        - services_install
        - system_config
        
    - role: network_config
      tags:
        - network_infra
        - foundation
        
    - role: netboot  
      tags:
        - services_install
        - dns_dhcp
        
    - role: web
      tags:
        - services_install
        - web_config
        
    - role: iso_preparation
      tags:
        - iso_management
        - expensive
      vars:
        use_async_downloads: true
        
    - role: validation
      tags:
        - validation
        - health_check
      when: validation_enabled | default(true)

  post_tasks:
    - name: Deploy and run state population script
      block:
        - name: Deploy state population helper script
          template:
            src: roles/web/templates/populate_state.py.j2
            dest: "{{ nginx_web_root }}/scripts/populate_state.py"
            owner: www-data
            group: www-data
            mode: "0755"
            
        - name: Run state population script
          command: python3 {{ nginx_web_root }}/scripts/populate_state.py
          register: populate_result
          changed_when: "'New entries created:' in populate_result.stdout and not populate_result.stdout.split('New entries created: ')[1].split('\n')[0].strip().startswith('0')"
          
        - name: Display state population results
          debug:
            msg: "{{ populate_result.stdout_lines }}"
      tags:
        - state_population
        - web_config
        
    - name: Consolidated service restart
      block:
        - name: Restart all modified services
          systemd:
            name: "{{ item }}"
            state: restarted
            daemon_reload: yes
          loop: "{{ services_to_restart | default([]) }}"
          when: services_to_restart is defined and services_to_restart | length > 0
          register: services_restarted
          
        - name: Wait for services to stabilize
          wait_for:
            port: "{{ item.port }}"
            host: 127.0.0.1
            state: started
            timeout: 30
          loop:
            - { service: 'dnsmasq', port: 53 }
            - { service: 'nginx', port: 80 }
          when: services_restarted.changed | default(false)
      tags:
        - services_restart
        
    - name: Final validation block
      block:
        - name: Run comprehensive validation
          include_tasks: roles/validation/tasks/main.yml
          when: run_final_validation | default(true)
      tags:
        - final_validation
        - never  # Only run when explicitly requested

  handlers:
    - name: restart dnsmasq
      systemd:
        name: dnsmasq
        state: restarted
      listen: "restart network services"
      
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
      listen: "restart web services"
      
    - name: restart php-fpm
      systemd:
        name: php8.3-fpm
        state: restarted
      listen: "restart web services"
      
    - name: apply netplan
      command: netplan apply
      listen: "reconfigure network"
      
    - name: restart systemd-networkd
      systemd:
        name: systemd-networkd
        state: restarted
      listen: "reconfigure network"