---
- name: Provisioning Server Setup
  hosts: localhost
  connection: local
  become: yes

  roles:
    - role: common
      tags: ['common']
    - network_config
    - netboot
    - web
    - iso_preparation
    - validation
