---
- name: Provisioning Server Setup
  hosts: localhost
  connection: local
  become: yes

  roles:
    - role: common
      tags: 
        # Legacy tags (backward compatibility)
        - common
        - packages
        - ssh_setup  
        - network_setup
        - docker_setup
        # New granular tags
        - initial
        - system_config
        - expensive
        - maintenance

    - role: network_config
      tags:
        # Legacy tags
        - network_config
        - network_setup
        # New granular tags
        - initial
        - network
        - config
        - maintenance

    - role: netboot  
      tags:
        # Legacy tags
        - netboot
        - pxe_setup
        # New granular tags
        - initial
        - config
        - dns_dhcp
        - maintenance
        - quick

    - role: web
      tags:
        # Legacy tags  
        - web
        - web_setup
        - autoinstall_templates
        # New granular tags
        - initial
        - config
        - web_services
        - autoinstall
        - maintenance
        - quick

    - role: iso_preparation
      tags:
        # Legacy tags
        - iso_preparation
        - iso_processing  
        # New granular tags
        - expensive
        - iso_management
        - maintenance

    - role: validation
      tags:
        # Legacy tags
        - validation
        # New granular tags
        - maintenance
        - quick
        - validation
