---
# Management machine setup for Kubespray deployment
- name: Install uv package manager
  shell: curl -LsSf https://astral.sh/uv/install.sh | sh
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/uv"
  become: false

- name: Add uv to PATH in bashrc
  lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: 'export PATH="$HOME/.local/bin:$PATH"'
    create: yes
  become: false

- name: Create kubespray directory
  file:
    path: "{{ kubespray_path }}"
    state: directory
    mode: '0755'
  become: false

- name: Clone Kubespray repository
  git:
    repo: https://github.com/kubernetes-sigs/kubespray.git
    dest: "{{ kubespray_path }}"
    version: master
    force: yes
  become: false

- name: Create Python virtual environment
  shell: |
    export PATH="{{ ansible_env.HOME }}/.local/bin:$PATH"
    cd {{ kubespray_path }}
    uv venv venv
  args:
    creates: "{{ kubespray_path }}/venv"
  become: false

- name: Install Kubespray requirements
  shell: |
    export PATH="{{ ansible_env.HOME }}/.local/bin:$PATH"
    cd {{ kubespray_path }}
    source venv/bin/activate
    uv pip install -r requirements.txt
  args:
    executable: /bin/bash
  become: false

- name: Create cluster inventory from template
  template:
    src: kubespray-inventory.ini.j2
    dest: "{{ kubespray_path }}/inventory/{{ cluster_name }}/inventory.ini"
    mode: '0644'
  become: false

- name: Create cluster configuration directory
  file:
    path: "{{ kubespray_path }}/inventory/{{ cluster_name }}/group_vars/k8s_cluster"
    state: directory
    mode: '0755'
    recurse: yes
  become: false

- name: Copy sample configuration files
  shell: |
    cd {{ kubespray_path }}
    cp -rfp inventory/sample inventory/{{ cluster_name }}
  args:
    creates: "{{ kubespray_path }}/inventory/{{ cluster_name }}/group_vars"
  become: false

- name: Set inventory_dir fact
  set_fact:
    inventory_dir: "{{ kubespray_path }}/inventory/{{ cluster_name }}"

- name: Load Kubespray default variables
  include_vars:
    file: "{{ kubespray_path }}/roles/kubespray_defaults/defaults/main/main.yml"

- name: Set cluster_name fact
  set_fact:
    cluster_name: "mycluster"

- name: Set kube_pods_subnet fact
  set_fact:
    kube_pods_subnet: "{{ pod_network_cidr }}"

- name: Configure Kubernetes cluster settings
  template:
    src: k8s-cluster.yml.j2
    dest: "{{ kubespray_path }}/inventory/{{ cluster_name }}/group_vars/k8s_cluster/k8s-cluster.yml"
    mode: '0644'
  become: false

- name: Create kubespray deployment script
  template:
    src: deploy-cluster.sh.j2
    dest: "{{ kubespray_path }}/deploy-cluster.sh"
    mode: '0755'
  become: false