---
- name: restart sshd
  ansible.builtin.service:
    name: ssh
    state: restarted

- name: systemd daemon reload
  ansible.builtin.systemd:
    daemon_reload: yes

- name: update grub
  ansible.builtin.command:
    cmd: update-grub
  register: grub_update_result

- name: update initramfs
  ansible.builtin.command:
    cmd: update-initramfs -u
  register: initramfs_update_result