---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600 # Cache is valid for 1 hour

- name: Install common packages
  apt:
    name:
      - vim
      - git
      - curl
      - wget
      - unzip
    state: present

- name: Generate SSH key pair for sysadmin user
  ansible.builtin.shell:
    cmd: "ssh-keygen -t ed25519 -f /home/sysadmin/.ssh/sysadmin_automation_key -N ''"
    creates: /home/sysadmin/.ssh/sysadmin_automation_key

- name: Generate SSH key pair for root user
  ansible.builtin.shell:
    cmd: "ssh-keygen -t ed25519 -f /root/.ssh/root_automation_key -N ''"
    creates: /root/.ssh/root_automation_key
  become: yes

- name: Read sysadmin public key
  ansible.builtin.slurp:
    src: /home/sysadmin/.ssh/sysadmin_automation_key.pub
  register: sysadmin_pub_key_file

- name: Read root public key
  ansible.builtin.slurp:
    src: /root/.ssh/root_automation_key.pub
  become: yes
  register: root_pub_key_file

- name: Set public keys as facts
  ansible.builtin.set_fact:
    sysadmin_pub_key: "{{ sysadmin_pub_key_file.content | b64decode }}"
    root_pub_key: "{{ root_pub_key_file.content | b64decode }}"

- name: Authorize new sysadmin key for local sysadmin user
  ansible.posix.authorized_key:
    user: sysadmin
    key: "{{ sysadmin_pub_key }}"
    state: present

- name: Authorize new root key for local root user
  ansible.posix.authorized_key:
    user: root
    key: "{{ root_pub_key }}"
    state: present
  become: yes

- name: Securely configure SSH daemon
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
    state: present
  notify: restart sshd

- name: Update all packages to the latest version
  apt:
    upgrade: dist
    autoremove: yes
    autoclean: yes

- name: Configure sysctl to disable IPv6 and enable IP forwarding
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: yes
    state: present
    reload: yes
  with_items:
    - { key: 'net.ipv6.conf.all.disable_ipv6', value: '1' }
    - { key: 'net.ipv6.conf.default.disable_ipv6', value: '1' }
    - { key: 'net.ipv4.ip_forward', value: '1' }



- name: Install packages for NAT
  apt:
    name:
      - iptables
      - iptables-persistent
    state: present

- name: Check if NAT rule exists
  ansible.builtin.shell: "iptables -t nat -C POSTROUTING -s 10.10.1.0/24 -o ens34 -j MASQUERADE -m comment --comment 'NAT for internal network'"
  register: nat_rule_check
  changed_when: false
  failed_when: false

- name: Set NAT rule for internal network
  ansible.builtin.shell: "iptables -t nat -A POSTROUTING -s 10.10.1.0/24 -o ens34 -j MASQUERADE -m comment --comment 'NAT for internal network'"
  when: nat_rule_check.rc != 0

- name: Persist iptables rules
  ansible.builtin.command:
    cmd: netfilter-persistent save
  changed_when: false