---
# Enterprise-grade validation and health checks
- name: System validation and health checks
  block:
    - name: Validate required directories exist
      ansible.builtin.stat:
        path: "{{ item }}"
      register: directory_checks
      loop:
        - /var/www/html
        - /var/www/html/sessions
        - /var/www/html/autoinstall_configs
        - /var/lib/tftpboot
      failed_when: not directory_checks.results | map(attribute='stat.exists') | list | all

    - name: Validate required services are running
      ansible.builtin.service_facts:
    
    - name: Check critical services status
      ansible.builtin.fail:
        msg: "Critical service {{ item }} is not running"
      loop:
        - dnsmasq
        - nginx
        - php8.3-fpm
      when: ansible_facts.services[item + '.service'].state != 'running'

    - name: Validate network connectivity
      ansible.builtin.wait_for:
        host: "{{ ansible_default_ipv4.address }}"
        port: "{{ item }}"
        timeout: 10
      loop:
        - 53   # DNS
        - 67   # DHCP
        - 69   # TFTP
        - 80   # HTTP
      register: port_checks

    - name: Validate DNS resolution
      ansible.builtin.command: "nslookup google.com {{ ansible_default_ipv4.address }}"
      register: dns_test
      changed_when: false
      failed_when: dns_test.rc != 0

    - name: Validate DHCP service
      ansible.builtin.command: "systemctl is-active dnsmasq"
      register: dhcp_status
      changed_when: false
      failed_when: dhcp_status.stdout != "active"

    - name: Log validation success
      ansible.builtin.debug:
        msg: "All system validation checks passed successfully"

  rescue:
    - name: Log validation failure
      ansible.builtin.debug:
        msg: "System validation failed - manual intervention required"
        
    - name: Create rollback flag
      ansible.builtin.file:
        path: /tmp/ansible_validation_failed
        state: touch
        mode: '0644'
        
    - name: Fail the play if validation fails
      ansible.builtin.fail:
        msg: "Critical system validation failed - deployment aborted"